[package]
name = "zfz"
version = "0.1.0"
authors = ["Purple Myst <PurpleMyst@users.noreply.github.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
crossterm = "0.19.0"
fuzzy-matcher = "0.3.7"
